import React from "react";
import {Table, TableCaption, Tbody, Th, Thead, Tr} from "@chakra-ui/react";

export const TableComponent: React.FC = ({children}) => (
    <Table variant={"simple"}>
        <TableCaption>
            Content generated by kafka flow
        </TableCaption>
        <Thead>
            <Tr>
                <Th>Account number</Th>
                <Th>Agency number</Th>
                <Th>Owner</Th>
                <Th>Bank Name</Th>
            </Tr>
        </Thead>
        <Tbody>
            {children}
        </Tbody>
    </Table>
)
